# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffbda9a76f8119836c368f8615fe9d8333021f028cc41e7a7a8222150d5102f6a894c1f042d064692f148fb5f6cfc1d56b2fa69f5356d05bac2ed3f40001db5

test:
  secret_key_base: 367e16186384eb56e2ba3c0de378b472fbc55db0be576d2b00db92ab8281cc460a0a255287790c44d204338ed9a06c4ef87b8dd21e16addaea853b1588d54604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
